---
title: "03_run_models"
author: "G. Perkins"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Run models

```{r cars}
# set up the standard inputs 
fid <- setup_folders("CanyonCreek")

in_dir <- fid$model_inputs0310[2]

fmat <- read.csv(file.path(fid$AOI_dir[2], "fuzzy_matrix_basic.csv" ))%>%
  dplyr::select(target, Pred, fVal)

# set up tuning (applies to all models)
best_tune <- fread(file.path (in_dir, "best_tuning.csv"))
mtry <- best_tune$mtry
min_n <- best_tune$min_n

# select reduced variables
reduced_vars <- read.csv(file.path(in_dir,  "reduced_covariate_list.csv")) %>% pull()

bgc_pts_subzone <- readRDS(file.path(fid$model_inputs0310[2], "model_input_pts.rds"))

```

## Run base model 

This runs the model with no balancing using the parameters generated in 02_prepare_model_inputs.R. 

Alternatively you can run a balance optimize option (see below) 


```{r pressure, echo=FALSE}

model_bgc <- lapply(names(bgc_pts_subzone), function(xx) {
  
  xx <- names(bgc_pts_subzone[1])
  
  alldat = bgc_pts_subzone[[xx]]
  
  outDir = file.path(fid$model_draft[2], xx)
  
  tdat <- alldat %>% mutate(slice = factor(slice))
  tdat <- tdat %>%
    dplyr::select(id, fnf, x, y, bgc_cat,mapunit1, mapunit2, position,
      transect_id, tid, slice, any_of(reduced_vars))
  
  tdat <- tdat[complete.cases(tdat[, 12:length(tdat)]), ]
  
  # run basic model (no smote and no downsample)
  #temp fix: 
  train_data <- tdat %>%
    filter(slice != 1)
  train_data = as.data.table(train_data)
  train_data <-  train_data[grep("ICHmc2_", mapunit1), ]
  train_data <- droplevels(train_data)
  
  baseout <-run_base_model(
      train_data,
      fuzz_matrix = fmat,
      mtry = 14, #mtry
      min_n = 7, #min_n
      use.neighbours = TRUE )
  
  write.csv(baseout, file.path(outDir, "acc_base_results.csv"))
  
  # generate model accuracy report
  model_report(baseout, outDir)
  
}
```


# Generate and accuracy report? 








# Alternatively Run the balance optimised version 

```{r}
# # # data lines
  train_data <- trDat %>%
    filter(slice != 1)#%>%
    #dplyr::select(-bgc_cat,-transect_id)

  train_data = as.data.table(trDat)
  train_data <-  train_data[grep("ICHmc2_",mapunit1),]
  train_data <- droplevels(train_data)

  fuzz_matrix = fmat
  num_slice = 4
   n_iters = 4
   use.neighbours = TRUE
   acc_mets = c("spat_paf_theta.5")
   mtry = 4 #mtry
   min_n = 7# min_n
   # end data lines

#metrics_to_run <- c("spat_paf_theta.5")

opt_res <- optimise_balance(train_data, 
                 fuzz_matrix, 
                 num_slice = 4, 
                 n_iters = 4, 
                 mtry = 14,
                 min_n = 7, 
                 use.neighbours = TRUE,
                 acc_mets = acc_mets)


# get best balance: 
getBestPars(opt_res, N = 5)

```


# Run the final model 

```{r}

model_bgc <- lapply(names(bgc_pts_subzone), function(xx) {
  
  xx <- names(bgc_pts_subzone[1])
  
  alldat = bgc_pts_subzone[[xx]]

  outDir = file.path(fid$model_final[2], xx)
 
  final_data <- alldat %>%
    dplyr::filter(position == "Orig") %>%
    dplyr::select(mapunit1, any_of(reduced_vars))
  
  final_data <-  final_data[complete.cases(tdat[, 2:length(final_data)]), ]

  # testing 
  final_data = as.data.table(final_data)
  final_data <-  final_data[grep("ICHmc2_", mapunit1), ]
  # end testing 
  
  final_model <- run_final_model(
      train_data,
      fuzz_matrix = fmat,
      mtry = 14, #mtry
      min_n = 7, #min_n
      ds_ratio = NULL, 
      sm_ratio = NULL)
  
  # Output model 
saveRDS(final_model, file.path(outDir, "final_model.rds"))

}


```



