---
title: "Model_report"
output: html_document
params:
  tpts: tpts
  out_dir: out_dir
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This model uses the following parameters: 

* **mapunit:** mapunit1
* **training point set : **
* **model response and covariates: ** 


The following training points and frequency of points were used in the model. 

```{r cars}

## Load library
library(data.table)
library(rmarkdown)
library(knitr)
library(dplyr)
library(ggplot2)

tpts <- params$tpts
out_dir <- params$out_dir

```


```{r summary, echo = FALSE, include = TRUE}

table(tpts[, "mapunit1"])

# calculate summary of raw training data set
trDat_sum <- tpts %>%
  dplyr::group_by(mapunit1) %>%
  dplyr::summarise(freq = n()) %>%
  dplyr::mutate(prop = round(freq/sum(freq),3))

ggplot(tpts, aes(mapunit1)) +
  geom_bar() + 
  theme_pem()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_discrete_sequential(palette = "Light Grays")

trDat_slices <- trDat %>%
  group_by (slice) %>%
  dplyr::summarise(n.transect = length(unique(transect_id)),
                   n.sites = length(unique(tid))) %>% 
  pivot_longer(cols = c("n.transect", "n.sites"), names_to = "type", values_to = "number")

ggplot(trDat_slices, aes(slice, number, fill = type)) +
  geom_bar(stat = "identity", position = "dodge") + 
  theme_pem()+
  scale_fill_discrete_sequential(palette = "Light Grays")

```


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
